


if(NOT SDL2_DIR)
#message(WARNING "SDL2_DIR not found!")
set(SDL2_DIR $ENV{SDL2_DIR} CACHE PATH "Choose SDL2 PATH" FORCE)
else(NOT SDL2_DIR)
find_path(SDL2_INCLUDE_DIR SDL.h ${SDL2_DIR}/include)
find_library(SDL2d_debug SDL2d.lib ${SDL2_DIR}/lib/Debug)
find_library(SDL2_release SDL2.lib ${SDL2_DIR}/lib/Release)
find_library(SDL2maind_debug SDL2maind.lib ${SDL2_DIR}/lib/Debug)
find_library(SDL2main_release SDL2main.lib ${SDL2_DIR}/lib/Release)
message(STATUS "********************SDL2*************************")
message(STATUS "SDL2_INCLUDE: " ${SDL2_INCLUDE_DIR})
message(STATUS "SDL2d_debug: " ${SDL2d_debug})
message(STATUS "SDL2_release: " ${SDL2_release})
message(STATUS "SDL2maind: " ${SDL2maind_debug})
message(STATUS "SDL2main: " ${SDL2main_release})
message(STATUS "********************SDL2-LIBS*************************")
set(SDL2_debug_libs ${SDL2d_debug} ${SDL2maind_debug})
set(SDL2_release_libs ${SDL2_release} ${SDL2main_release})
message(STATUS "debug: " ${SDL2_debug_libs})
message(STATUS "release: " ${SDL2_release_libs})
message(STATUS "********************END*************************")
endif(NOT SDL2_DIR)